version: "3"
services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - node-app-container
    node-app-container:
        image: pedro1840/myapp
        deploy:
            - replicas: 5
